pdb_tidy 1ao7_b.pdb | pdb_selchain -D,E> 1ao7_b_DE.pdb
pdb_tidy 1mi5_b.pdb | pdb_selchain -D,E> 1mi5_b_DE.pdb
pdb_tidy 1mwa_b.pdb | pdb_selchain -D,E> 1mwa_b_DE.pdb
pdb_tidy 1oga_b.pdb | pdb_selchain -D,E> 1oga_b_DE.pdb
pdb_tidy 2bnr_b.pdb | pdb_selchain -D,E> 2bnr_b_DE.pdb
pdb_tidy 2ckb_b.pdb | pdb_selchain -D,E> 2ckb_b_DE.pdb
pdb_tidy 2nx5_b.pdb | pdb_selchain -D,E> 2nx5_b_DE.pdb
pdb_tidy 2oi9_b.pdb | pdb_selchain -D,E> 2oi9_b_DE.pdb
pdb_tidy 2pye_b.pdb | pdb_selchain -D,E> 2pye_b_DE.pdb
pdb_tidy 3dxa_b.pdb | pdb_selchain -D,E> 3dxa_b_DE.pdb
pdb_tidy 3h9s_b.pdb | pdb_selchain -D,E> 3h9s_b_DE.pdb
pdb_tidy 3kpr_b.pdb | pdb_selchain -D,E> 3kpr_b_DE.pdb
pdb_tidy 3kps_b.pdb | pdb_selchain -D,E> 3kps_b_DE.pdb
pdb_tidy 3pwp_b.pdb | pdb_selchain -D,E> 3pwp_b_DE.pdb
pdb_tidy 3qdg_b.pdb | pdb_selchain -D,E> 3qdg_b_DE.pdb
pdb_tidy 3qdj_b.pdb | pdb_selchain -D,E> 3qdj_b_DE.pdb
pdb_tidy 3sjv_b.pdb | pdb_selchain -D,E> 3sjv_b_DE.pdb
pdb_tidy 3utt_b.pdb | pdb_selchain -D,E> 3utt_b_DE.pdb
pdb_tidy 3vxr_b.pdb | pdb_selchain -D,E> 3vxr_b_DE.pdb
pdb_tidy 3vxs_b.pdb | pdb_selchain -D,E> 3vxs_b_DE.pdb
pdb_tidy 3w0w_b.pdb | pdb_selchain -D,E> 3w0w_b_DE.pdb
pdb_tidy 4jfd_b.pdb | pdb_selchain -D,E> 4jfd_b_DE.pdb
pdb_tidy 4jff_b.pdb | pdb_selchain -D,E> 4jff_b_DE.pdb
pdb_tidy 5c07_b.pdb | pdb_selchain -D,E> 5c07_b_DE.pdb
pdb_tidy 5c08_b.pdb | pdb_selchain -D,E> 5c08_b_DE.pdb
pdb_tidy 5c09_b.pdb | pdb_selchain -D,E> 5c09_b_DE.pdb
pdb_tidy 5c0a_b.pdb | pdb_selchain -D,E> 5c0a_b_DE.pdb
pdb_tidy 5c0b_b.pdb | pdb_selchain -D,E> 5c0b_b_DE.pdb
pdb_tidy 5c0c_b.pdb | pdb_selchain -D,E> 5c0c_b_DE.pdb
pdb_tidy 5hhm_b.pdb | pdb_selchain -D,E> 5hhm_b_DE.pdb
pdb_tidy 5hyj_b.pdb | pdb_selchain -D,E> 5hyj_b_DE.pdb
pdb_tidy 5ivx_b.pdb | pdb_selchain -D,E> 5ivx_b_DE.pdb
pdb_tidy 5nme_b.pdb | pdb_selchain -D,E> 5nme_b_DE.pdb
pdb_tidy 5nmf_b.pdb | pdb_selchain -D,E> 5nmf_b_DE.pdb
pdb_tidy 5nmg_b.pdb | pdb_selchain -D,E> 5nmg_b_DE.pdb
pdb_tidy 6amu_b.pdb | pdb_selchain -D,E> 6amu_b_DE.pdb
pdb_tidy 6avf_b.pdb | pdb_selchain -D,E> 6avf_b_DE.pdb
pdb_tidy 6eqb_b.pdb | pdb_selchain -D,E> 6eqb_b_DE.pdb
